server:
  port: 8091

#logging:
#  level:
#    root: info

spring:
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  #配置数据库
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ies_ls?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 在映射实体或属性时，将数据库中的下划线转换为驼峰命名
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: assign_id

getTokenUser: fuzhou

ots:
  endpoint: https://r01m5bxkue4q.cn-hangzhou.ots.aliyuncs.com
  instance_name: r01m5bxkue4q
  access_key_id: LTAI5tRHP6E9o1bh7MZY7JXj
  access_key_secret: AEqi82fg2wI1LK3bKgnOH43O67791l
  table_name: dyyc
  key: key
  curve-template-path: 曲线.json

# excel导出路径
excel:
  export-path: C:\\Users\\GXL\\Desktop\\工作\\
  file-name: 四区主站-中压-巡检记录表2025.xlsx

  #export-path: C:\\Users\\Administrator\\Desktop\\工作\\

# 图模文件路径
tumo:
  paths:
    zytumo: C:\\Users\\GXL\\Desktop\\工作\\zytumo\\{date}\\
    dytumo: C:\\Users\\GXL\\Desktop\\工作\\dytumo\\{date}\\
city:
  cities:
    35401: 福州
    35402: 厦门
    35405: 泉州
    35406: 漳州
    35407: 龙岩
    35408: 三明
    35409: 南平
    35403: 宁德
    35404: 莆田

areas:
  area:
    #0: 全省
    3096224743817217: 福州市
    3096224760594433: 厦门市
    3096224777371649: 泉州市
    3096224794148865: 漳州市
    3096224810926081: 龙岩市
    3096224827703297: 三明市
    3096224844480513: 宁德市
    3096224861257729: 南平市
    3096224878034945: 莆田市

app:
  auth:
    session-never-expire: true
  file:
    monitor:
      enabled: true
      default-check-interval: 30
      default-max-concurrent: 5
      default-stability-threshold: 10000
      configs:
        # - id: csv-uploads
        #   directory: C:\Users\29260\Desktop\工作\csv\
        #   file-pattern: "*.csv"
        #   check-interval: 10
        #   stability-threshold: 2000
        - id: jar-uploads
          directory: C:\Users\GXL\Desktop\工作\jar\
          file-pattern: "*.jar"
          recursive: false
          check-interval: 15
          stability-threshold: 5000
        - id: nginx-uploads
          directory: C:\Users\GXL\Desktop\工作\jar\
          file-pattern: "*.zip"
          recursive: false
          check-interval: 15
          stability-threshold: 5000
        - id: topo-uploads
          directory: C:\Users\GXL\Desktop\工作\topo\
          customProperties:
            encoding: GBK
          file-pattern: "*.inf"
          recursive: false
          check-interval: 10
          stability-threshold: 5000
        - id: xs-topo-uploads
          directory: C:\Users\GXL\Desktop\工作\topo\
          file-pattern: "*.log"
          recursive: false
          check-interval: 10
          stability-threshold: 5000
        # - id: breaker-energy-uploads
        #   directory: C:\Users\GXL\Desktop\工作\energy\
        #   file-pattern: "*.txt"
        #   recursive: false
        #   check-interval: 10
        #   stability-threshold: 5000
        - id: connectivity-uploads
          directory: C:\Users\GXL\Desktop\工作\energy\
          file-pattern: "*.xlsx"
          recursive: false
          check-interval: 10
          stability-threshold: 5000
server-connections:
  idle-timeout-minutes: 0
  cleanup-delay-ms: 60000
  ssh-keepalive-interval-seconds: 30



jar:
  scan:
    path: C:\\Users\\GXL\\Desktop\\工作\\jar\\
  target:
    path: /home/ies/webserver/dmscld/bin/
  nginx:
    path: /home/ies/webserver/nginx/html/

inspection:
  servers:
    - ip: 127.0.0.1
      port: 15353
      username: gxl
      password: 123456
      jars:
        - CommonUtil-0.0.1-SNAPSHOT.jar:commonUtil.sh
        - dmscldpro:null
        - dmscldprotest:null
    - ip: 127.0.0.1
      port: 15353
      username: gxl
      password: 123456
      jars:
        - CommonUtil.jar:commonUtil.sh

commands:
  command:
    CPU_USAGE: top -b -n 1 -p 1 | sed -n '3p' | awk '{print $2}'| sort -nrk 1 | head -n 1
    MEMORY_USAGE_RATE: free -m | grep Mem | awk '{print $3/$2 * 100.0}'
    MEMORY_USAGE: free -h | sed -n '2p' | awk '{print $3}'
    MEMORY_TOTAL: free -h | sed -n '2p' | awk '{print $2}'
    DISK_USAGE: df -h | grep /dev/vda | awk '{print $3}'
    DISK_TOTAL: df -h | grep /dev/vda | awk '{print $2}'
    DISK_USAGE_RATE: df -h | grep /dev/vda | awk '{print $5}'
    JPS_PATH: which jps
    JAVA_PROCESSES: " | awk '{print $2}'"
    THREAD_COUNT: ps -elf | wc -l
    SECOND_DISK_USAGE_RATE: df -h | grep /dev/vdb1| awk '{print $5}'
    SECOND_DISK_USAGE: df -h | grep /dev/vdb1| awk '{print $3}'
    SECOND_DISK_TOTAL: df -h | grep /dev/vdb1| awk '{print $2}'
    SECOND_DISK_USAGE_RATE_209: df -h | grep /dev
    SECOND_DISK_USAGE_209: df -h | grep /dev
    SECOND_DISK_TOTAL_209: df -h | grep /dev
    THIRD_DISK_USAGE_RATE: df -h | grep /dev/vdc1| awk '{print $5}'
    THIRD_DISK_USAGE: df -h | grep /dev/vdc1| awk '{print $3}'
    THIRD_DISK_TOTAL: df -h | grep /dev/vdc1| awk '{print $2}'
